### ISSUE TITLE
StackOverflowException caused  by MStatReportWorker collect failed.

### ISSUE THREAD

**Issue by terry19850829** [ltsopensource/light-task-scheduler#299]
2016-07-10 00:00:00[LTS-Monitor-data-collector-thread-1:286184274]-[ERROR]         [LTS]MStatReportWorker collect failed., lts version: 1.6.8, current host: 192.168.111.112
    java.lang.StackOverflowError
	at java.util.ArrayList$SubList.add(ArrayList.java:1047)
	at java.util.ArrayList$SubList.add(ArrayList.java:1047)
        .... 

ArrayList size > 3000000

**Comment by terry19850829** [comment]
这个统计监控是否可以显示关闭？？

**Comment by qq254963746** [comment]
我默认是最多500条，怎么会有这么多, 我看看

**Comment by terry19850829** [comment]
@qq254963746 如果服务端没有开处理这个Collector队列里面的数据，你这边的代码是每次移除最老的500个数据，如果积累的速度远远大于500的话，会不会撑爆内存？

    int size = mDataQueue.size();
        if (size > MAX_RETRY_RETAIN) {  // >500 remove 500
            // delete the oldest
            mDataQueue = mDataQueue.subList(size - MAX_RETRY_RETAIN, size);
        }

**Comment by qq254963746** [comment]
@terry19850829 不是移除500，是只留500

**Comment by terry19850829** [comment]
@qq254963746  对，看错代码了。那这个是什么原因导致的 。。。

**Comment by terry19850829** [comment]
@qq254963746  这个issue在开启监控的情况也是会发生的，不知道原因找到没
