### ISSUE TITLE
执行任务失败

### ISSUE THREAD

**Issue by vylan** [ltsopensource/light-task-scheduler#350]
错误信息如下：

`2017-05-02 20:27:30,589 [AbstractClientNode-thread-6] (AbstractRemoting.java:101) ERROR com.github.ltsopensource.remoting.AbstractRemoting  -  [LTS] RemotingCommand{code=13, subCode=0, version=0, opaque=194984, flag=0, remark='null', sid='-1', body={"identity":"JT_210.14.69.95_28137_10-07-58.103_1","nodeGroup":"lts","nodeType":"JOB_TRACKER","timestamp":1493728037825}}, lts version: 1.7.0, current host: 10.200.45.130
2017-05-02 20:27:32,601 [AbstractClientNode-thread-7] (AbstractRemoting.java:100) ERROR com.github.ltsopensource.remoting.AbstractRemoting  -  [LTS] process request exception, lts version: 1.7.0, current host: 10.200.45.130
java.lang.NullPointerException
	at com.github.ltsopensource.tasktracker.processor.JobPushProcessor.processRequest(JobPushProcessor.java:92)
	at com.github.ltsopensource.tasktracker.processor.RemotingDispatcher.processRequest(RemotingDispatcher.java:37)
	at com.github.ltsopensource.remoting.AbstractRemoting$1.run(AbstractRemoting.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by vylan** [comment]
降为1.6.9时错误消失。

**Comment by zhaoyuguang** [comment]
我也遇到过 将左右包升级到1.7.0就好了
