### ISSUE TITLE
no leveldbjni in java.library.path

### ISSUE THREAD

**Issue by panguicai008** [ltsopensource/light-task-scheduler#380]
java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni64-1.8 in 
java.library.path, no leveldbjni-1.8 in java.library.path, no leveldbjni in java.library.path, C:\Users\panguicai\AppData\Local\Temp\leveldbjni-64-1-5667873143997753877.8: %1 不是有效的 Win32 应用程序。]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.fusesource.leveldbjni.JniDBFactory.<clinit>(JniDBFactory.java:48)
	at com.github.ltsopensource.core.failstore.leveldb.LeveldbFailStore.open(LeveldbFailStore.java:54)
	at com.github.ltsopensource.core.support.RetryScheduler.<init>(RetryScheduler.java:64)
	at com.github.ltsopensource.core.support.RetryScheduler.<init>(RetryScheduler.java:89)
	at com.github.ltsopensource.jobclient.RetryJobClient$1.<init>(RetryJobClient.java:28)
	at com.github.ltsopensource.jobclient.RetryJobClient.beforeStart(RetryJobClient.java:27)
	at com.github.ltsopensource.core.cluster.AbstractClientNode.beforeRemotingStart(AbstractClientNode.java:66)
	at com.github.ltsopensource.core.cluster.AbstractJobNode.start(AbstractJobNode.java:74)
	at com.github.ltsopensource.spring.JobClientFactoryBean.start(JobClientFactoryBean.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1706)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1645)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1054)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1019)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by arvindiy** [comment]
Did you find a solution to this problem ?

I am hitting the following error

15:44:02.517 [log-ingestor-akka.actor.default-dispatcher-22] ERROR akka.actor.ActorSystemImpl - Uncaught error from thread [log-ingestor-akka.persistence.dispatchers.default-plugin-dispatcher-23]: Could not load library. Reasons: [no leveldbjni64-1.8 in java.library.path, no leveldbjni-1.8 in java.library.path, no leveldbjni in java.library.path, Permission denied], shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[log-ingestor]
java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni64-1.8 in java.library.path, no leveldbjni-1.8 in java.library.path, no leveldbjni in java.library.path, Permission denied]
        at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182) ~[leveldbjni-all-1.8.jar:1.8]
        at org.fusesource.hawtjni.runtime.Library.load(Library.java:140) ~[leveldbjni-all-1.8.jar:1.8]
        at org.fusesource.leveldbjni.JniDBFactory.<clinit>(JniDBFactory.java:48) ~[leveldbjni-all-1.8.jar:1.8]
        at akka.persistence.journal.leveldb.LeveldbStore$class.leveldbFactory(LeveldbStore.scala:52) ~[akka-persistence_2.11-2.5.4.jar:na]
        at akka.persistence.journal.leveldb.LeveldbJournal.leveldbFactory(LeveldbJournal.scala:23) ~[akka-persistence_2.11-2.5.4.jar:na]
        at akka.persistence.journal.leveldb.LeveldbStore$class.preStart(LeveldbStore.scala:178) ~[akka-persistence_2.11-2.5.4.jar:na]
        at akka.persistence.journal.leveldb.LeveldbJournal.preStart(LeveldbJournal.scala:23) ~[akka-persistence_2.11-2.5.4.jar:na]
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:522) ~[akka-actor_2.11-2.5.4.jar:na]
        at akka.persistence.journal.leveldb.LeveldbJournal.aroundPreStart(LeveldbJournal.scala:23) ~[akka-persistence_2.11-2.5.4.jar:na]
        at akka.actor.ActorCell.create(ActorCell.scala:591) ~[akka-actor_2.11-2.5.4.jar:na]

**Comment by panguicai008** [comment]
You can use win7 os instead of win10

**Comment by arvindiy** [comment]
I am sorry. I didnt provide more information than just the exception stack trace. I am using centos:6.9 image in a docker container. 

These are my akka configurations for leveldb persistence
 akka.persistence.journal.plugin = "akka.persistence.journal.leveldb"
    akka.persistence.snapshot-store.plugin = "akka.persistence.snapshot-store.local"
    akka.persistence.journal.leveldb.native = true
    akka.persistence.snapshot-store.local.dir = "data/snapshots"
    akka.persistence.journal.leveldb.dir = "data/journal"


I am not running this application as the 'root' user, inside the docker container. Inside the DockerFile, I also have the following lines of code, to run it as a particular user

    RUN useradd -ms /bin/bash portal-admin
    USER portal-admin
    WORKDIR /home/portal-admin
    RUN chown portal-admin /home/portal-admin
