### ISSUE TITLE
lts-admin启动报错

### ISSUE THREAD

**Issue by ROBOSI** [ltsopensource/light-task-scheduler#390]
log4j:WARN No appenders could be found for logger (org.mortbay.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
lts.admin.config.path : /Users/yanjintao/Desktop/WorkSpace/light-task-scheduler-master/dist/lts-1.7.1-SNAPSHOT-bin/conf
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/yanjintao/Desktop/WorkSpace/light-task-scheduler-master/dist/lts-1.7.1-SNAPSHOT-bin/war/jetty/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/private/var/folders/0f/3rg796xs7sxgjn1py8mzshxw0000gn/T/Jetty_0_0_0_0_8081_lts.admin.war____htq1ft/webapp/WEB-INF/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
[INFO ] [18:34:30] com.github.ltsopensource.core.logger.LoggerFactory - using logger: com.github.ltsopensource.core.logger.slf4j.Slf4jLoggerAdapter
[INFO ] [18:34:30] com.github.ltsopensource.core.logger.LoggerFactory - using logger: com.github.ltsopensource.core.logger.slf4j.Slf4jLoggerAdapter
[ERROR] [18:34:30] com.github.ltsopensource.core.support.Version -  [LTS] Duplicate class com/github/ltsopensource/core/support/Version.class in 2 jar [file:/Users/yanjintao/Desktop/WorkSpace/light-task-scheduler-master/dist/lts-1.7.1-SNAPSHOT-bin/war/jetty/lib/lts-core-1.7.1-SNAPSHOT.jar!/com/github/ltsopensource/core/support/Version.class, file:/private/var/folders/0f/3rg796xs7sxgjn1py8mzshxw0000gn/T/Jetty_0_0_0_0_8081_lts.admin.war____htq1ft/webapp/WEB-INF/lib/lts-core-1.7.1-SNAPSHOT.jar!/com/github/ltsopensource/core/support/Version.class], lts version: 1.7.1-SNAPSHOT, current host: 10.10.168.215
[ERROR] [18:34:30] com.github.ltsopensource.monitor.MonitorAgent -  [LTS] ========== Start Monitor Error:, lts version: 1.7.1-SNAPSHOT, current host: 10.10.168.215
java.lang.IllegalStateException: Service loader could not load name:mysql  class:com.github.ltsopensource.store.jdbc.datasource.DataSourceProvider's ServiceProvider from 'META-INF/lts/' or 'META-INF/lts/internal/' It may be empty or does not exist.
	at com.github.ltsopensource.core.spi.ServiceLoader.load(ServiceLoader.java:92)
	at com.github.ltsopensource.core.spi.ServiceLoader.load(ServiceLoader.java:40)
	at com.github.ltsopensource.store.jdbc.SqlTemplateFactory.create(SqlTemplateFactory.java:21)
	at com.github.ltsopensource.store.jdbc.JdbcAbstractAccess.<init>(JdbcAbstractAccess.java:23)
	at com.github.ltsopensource.monitor.access.mysql.MysqlAbstractJdbcAccess.<init>(MysqlAbstractJdbcAccess.java:12)
	at com.github.ltsopensource.monitor.access.mysql.MysqlJobTrackerMAccess.<init>(MysqlJobTrackerMAccess.java:16)
	at com.github.ltsopensource.monitor.access.mysql.MysqlMonitorAccessFactory.getJobTrackerMAccess(MysqlMonitorAccessFactory.java:14)
	at com.github.ltsopensource.monitor.MonitorAgent.intConfig(MonitorAgent.java:124)
	at com.github.ltsopensource.monitor.MonitorAgent.start(MonitorAgent.java:60)
	at com.github.ltsopensource.monitor.MonitorAgentStartup.start(MonitorAgentStartup.java:42)
	at com.github.ltsopensource.admin.support.SystemInitListener.contextInitialized(SystemInitListener.java:61)
	at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:549)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:136)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.github.ltsopensource.startup.admin.JettyContainer.main(JettyContainer.java:46)
[INFO ] [18:34:30] / - Initializing Spring root WebApplicationContext
[INFO ] [18:34:30] org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization started
[INFO ] [18:34:30] org.springframework.web.context.support.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Wed Nov 08 18:34:30 CST 2017]; root of context hierarchy
[INFO ] [18:34:30] org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [spring-core.xml]
[WARN ] [18:34:31] org.springframework.web.context.support.XmlWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appContext' defined in class path resource [spring-core.xml]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Service loader could not load name:mysql  class:com.github.ltsopensource.store.jdbc.datasource.DataSourceProvider's ServiceProvider from 'META-INF/lts/' or 'META-INF/lts/internal/' It may be empty or does not exist.
[ERROR] [18:34:31] org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appContext' defined in class path resource [spring-core.xml]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Service loader could not load name:mysql  class:com.github.ltsopensource.store.jdbc.datasource.DataSourceProvider's ServiceProvider from 'META-INF/lts/' or 'META-INF/lts/internal/' It may be empty or does not exist.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:753)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:549)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:136)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.github.ltsopensource.startup.admin.JettyContainer.main(JettyContainer.java:46)
Caused by: java.lang.IllegalStateException: Service loader could not load name:mysql  class:com.github.ltsopensource.store.jdbc.datasource.DataSourceProvider's ServiceProvider from 'META-INF/lts/' or 'META-INF/lts/internal/' It may be empty or does not exist.
	at com.github.ltsopensource.core.spi.ServiceLoader.load(ServiceLoader.java:92)
	at com.github.ltsopensource.core.spi.ServiceLoader.load(ServiceLoader.java:40)
	at com.github.ltsopensource.store.jdbc.SqlTemplateFactory.create(SqlTemplateFactory.java:21)
	at com.github.ltsopensource.store.jdbc.JdbcAbstractAccess.<init>(JdbcAbstractAccess.java:23)
	at com.github.ltsopensource.monitor.access.mysql.MysqlAbstractJdbcAccess.<init>(MysqlAbstractJdbcAccess.java:12)
	at com.github.ltsopensource.monitor.access.mysql.MysqlJobClientMAccess.<init>(MysqlJobClientMAccess.java:17)
	at com.github.ltsopensource.admin.access.mysql.MysqlBackendJobClientMAccess.<init>(MysqlBackendJobClientMAccess.java:22)
	at com.github.ltsopensource.admin.access.mysql.MysqlBackendAccessFactory.getBackendJobClientMAccess(MysqlBackendAccessFactory.java:18)
	at com.github.ltsopensource.admin.support.BackendAppContextFactoryBean.initAccess(BackendAppContextFactoryBean.java:112)
	at com.github.ltsopensource.admin.support.BackendAppContextFactoryBean.afterPropertiesSet(BackendAppContextFactoryBean.java:80)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 22 more
[ERROR] [18:34:31] org.mortbay.log - Failed startup of context org.mortbay.jetty.webapp.WebAppContext@1376c05c{/,/Users/yanjintao/Desktop/WorkSpace/light-task-scheduler-master/dist/lts-1.7.1-SNAPSHOT-bin/war/lts-admin.war}
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appContext' defined in class path resource [spring-core.xml]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Service loader could not load name:mysql  class:com.github.ltsopensource.store.jdbc.datasource.DataSourceProvider's ServiceProvider from 'META-INF/lts/' or 'META-INF/lts/internal/' It may be empty or does not exist.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:753)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:549)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:136)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.github.ltsopensource.startup.admin.JettyContainer.main(JettyContainer.java:46)
Caused by: java.lang.IllegalStateException: Service loader could not load name:mysql  class:com.github.ltsopensource.store.jdbc.datasource.DataSourceProvider's ServiceProvider from 'META-INF/lts/' or 'META-INF/lts/internal/' It may be empty or does not exist.
	at com.github.ltsopensource.core.spi.ServiceLoader.load(ServiceLoader.java:92)
	at com.github.ltsopensource.core.spi.ServiceLoader.load(ServiceLoader.java:40)
	at com.github.ltsopensource.store.jdbc.SqlTemplateFactory.create(SqlTemplateFactory.java:21)
	at com.github.ltsopensource.store.jdbc.JdbcAbstractAccess.<init>(JdbcAbstractAccess.java:23)
	at com.github.ltsopensource.monitor.access.mysql.MysqlAbstractJdbcAccess.<init>(MysqlAbstractJdbcAccess.java:12)
	at com.github.ltsopensource.monitor.access.mysql.MysqlJobClientMAccess.<init>(MysqlJobClientMAccess.java:17)
	at com.github.ltsopensource.admin.access.mysql.MysqlBackendJobClientMAccess.<init>(MysqlBackendJobClientMAccess.java:22)
	at com.github.ltsopensource.admin.access.mysql.MysqlBackendAccessFactory.getBackendJobClientMAccess(MysqlBackendAccessFactory.java:18)
	at com.github.ltsopensource.admin.support.BackendAppContextFactoryBean.initAccess(BackendAppContextFactoryBean.java:112)
	at com.github.ltsopensource.admin.support.BackendAppContextFactoryBean.afterPropertiesSet(BackendAppContextFactoryBean.java:80)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 22 more
[ERROR] [18:34:31] org.mortbay.log - Nested in org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appContext' defined in class path resource [spring-core.xml]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Service loader could not load name:mysql  class:com.github.ltsopensource.store.jdbc.datasource.DataSourceProvider's ServiceProvider from 'META-INF/lts/' or 'META-INF/lts/internal/' It may be empty or does not exist.:
java.lang.IllegalStateException: Service loader could not load name:mysql  class:com.github.ltsopensource.store.jdbc.datasource.DataSourceProvider's ServiceProvider from 'META-INF/lts/' or 'META-INF/lts/internal/' It may be empty or does not exist.
	at com.github.ltsopensource.core.spi.ServiceLoader.load(ServiceLoader.java:92)
	at com.github.ltsopensource.core.spi.ServiceLoader.load(ServiceLoader.java:40)
	at com.github.ltsopensource.store.jdbc.SqlTemplateFactory.create(SqlTemplateFactory.java:21)
	at com.github.ltsopensource.store.jdbc.JdbcAbstractAccess.<init>(JdbcAbstractAccess.java:23)
	at com.github.ltsopensource.monitor.access.mysql.MysqlAbstractJdbcAccess.<init>(MysqlAbstractJdbcAccess.java:12)
	at com.github.ltsopensource.monitor.access.mysql.MysqlJobClientMAccess.<init>(MysqlJobClientMAccess.java:17)
	at com.github.ltsopensource.admin.access.mysql.MysqlBackendJobClientMAccess.<init>(MysqlBackendJobClientMAccess.java:22)
	at com.github.ltsopensource.admin.access.mysql.MysqlBackendAccessFactory.getBackendJobClientMAccess(MysqlBackendAccessFactory.java:18)
	at com.github.ltsopensource.admin.support.BackendAppContextFactoryBean.initAccess(BackendAppContextFactoryBean.java:112)
	at com.github.ltsopensource.admin.support.BackendAppContextFactoryBean.afterPropertiesSet(BackendAppContextFactoryBean.java:80)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:753)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:549)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:136)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.github.ltsopensource.startup.admin.JettyContainer.main(JettyContainer.java:46)
[INFO ] [18:34:31] org.mortbay.log - Started SocketConnector@0.0.0.0:8081

**Comment by Invincibled** [comment]
你解决了么，我也遇到了相同问题
