### ISSUE TITLE
build后在bin下面的lts-admin.cmd报错

### ISSUE THREAD

**Issue by jaoyina** [ltsopensource/light-task-scheduler#418]
A subdirectory or file D:\light-task-scheduler-master\light-task-scheduler-master\dist\lts-1.7.2-SNAPSHOT-bin\bin\..\\logs already exists.
LTS-Admin started
2018-09-06 19:24:05.321:INFO::Logging to STDERR via org.mortbay.log.StdErrLog
2018-09-06 19:24:05.368:INFO::jetty-6.1.26
2018-09-06 19:24:05.478:INFO::NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2018-09-06 19:24:05.564:INFO::Started SocketConnector@0.0.0.0:8081
LTS-Admin started. http://172.16.241.81:8081/index.htm

打开后是404，感觉没起来。这是为啥？

**Comment by JDFISH** [comment]
HTTP ERROR 503
Problem accessing /index.htm. Reason:

    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter#0' defined in class path resource [spring-web.xml]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
Caused by:
javax.servlet.UnavailableException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter#0' defined in class path resource [spring-web.xml]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.mortbay.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:415)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:458)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:736)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.github.ltsopensource.startup.admin.JettyContainer.main(JettyContainer.java:46)

**Comment by Var-iazioni** [comment]
我也遇到这个问题了。。貌似是jetty跟jsp的问题。。
有人解决了么。。

**Comment by xcw931924821** [comment]
有人解决了吗，我也是404

**Comment by sevenDay2014** [comment]
您好，你发送的邮件我已经收到，尽快给您回复，如有急事，请随时电话联系！                                                 张付红                                                 tel:13265450448

**Comment by xcw931924821** [comment]
NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet 空白页面了
